sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=ganeshpote1988/devops
    - BASE_IMAGE=cartahub/devops

before_script:
  - docker pull "$BASE_IMAGE" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:develop" --tag "$IMAGE_NAME" .

after_script:
  - docker images
  - pip install -r /carta/devops/requirements.txt
  - python /carta/devops/tests/*

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}-develop"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}-develop"
  on:
    branch: master
