sudo: true
dist: trusty

env:
  global:
    - $IMAGE_NAME: dockerpoc
    - $DOCKER_USERNAME: gandhir26
    - $DOCKER_PASSWORD: Microsoft@123
    - $DOCKER_PUSH: gandhir26/dockerpoc
   
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t ${DOCKER_PUSH}:7 .
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_PUSH
      - sudo apt-get update -y
      - sudo apt-get install curl
      - sudo apt-get install apt-transport-https
      - sudo apt install virtualbox virtualbox-ext-pack
      - wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      - sudo cp minikube-linux-amd64 /usr/local/bin/minikube
      - sudo chmod 755 /usr/local/bin/minikube
      - minikube version
      
    - stage: Kubernetes Install
      script: 
      - sudo mkdir -p /usr/local/bin/
      - sudo install minikube
   

