sudo: true
dist: trusty

env:
  global:
    - $IMAGE_NAME: dockerpoc
    - $DOCKER_USERNAME: gandhir26
    - $DOCKER_PASSWORD: Microsoft@123
    - $DOCKER_PUSH: gandhir26/dockerpoc
   
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t ${DOCKER_PUSH}:7 .
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_PUSH
      - sudo mkdir -p /usr/local/bin/
      - sudo install minikube /usr/local/bin/
      
    - stage: Kubernetes Install
      script: 
      - sudo mkdir -p /usr/local/bin/
      - sudo install minikube
   

