sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=cartahub/devops

before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "${IMAGE_NAME}:develop" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}-develop"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}-develop"
  on:
    branch: master
