sudo: true
dist: trusty

env:
  global:
    - $IMAGE_NAME: dockerpoc
    - $DOCKER_USERNAME: gandhir26
    - $DOCKER_PASSWORD: Microsoft@123
   
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t image:gandhir26 .
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/${BASE_IMAGE} cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/${BASE_IMAGE} cat hello.txt
