apiVersion: v1
kind: Service
metadata:
  name: carta-devops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: carta-devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carta-devops
  template:
    metadata:
      labels:
        app: carta-devops
    spec:
      containers:
      - name: carta-devops
        image: gandhir26/dockerpoc
        ports:
        - containerPort: 8080
